### ISSUE TITLE
Can't start tomate-gtk in Ubuntu 14.04

### ISSUE THREAD

**Issue by ewilazarus** [eliostvs/tomate-gtk#1]
$ tomate-gtk
    Traceback (most recent call last):
      File "/usr/bin/tomate-gtk", line 9, in <module>
        load_entry_point('tomate-gtk==0.3.0', 'console_scripts', 'tomate-gtk')()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 552, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
        return ep.load()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2345, in load
        return self.resolve()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2351, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/lib/python2.7/dist-packages/tomate_gtk/__main__.py", line 3, in <module>
        from .main import main
      File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 8, in <module>
        from tomate.app import application_factory
    ImportError: No module named tomate.app

**Comment by eliostvs** [comment]
Hello. Which version are you using? Execute:

    ls /usr/local/lib/python2.7/dist-packages/ | grep tomate

**Comment by eliostvs** [comment]
Hi, I released a new version today. Try do update and if you still have problems let me know.
