### ISSUE TITLE
Python 2 or 3

### ISSUE THREAD

**Issue by AlexTalker** [eliostvs/tomate-gtk#2]
Could you please specify which version of python required the project?
I've failed running the thing with python 3.
Because ConfigParser has been renamed in configparser as I can see:
```
/usr/bin/tomate-gtk:9: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  load_entry_point('tomate-gtk==0.3.0', 'console_scripts', 'tomate-gtk')()
/usr/lib/python3.5/site-packages/pkg_resources/__init__.py:2682: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  return ep.load()
/usr/lib/python3.5/site-packages/pkg_resources/__init__.py:558: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  return get_distribution(dist).load_entry_point(group, name)
ERROR:2015-10-24 12:21:48,019:tomate_gtk.main:No module named 'ConfigParser'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/tomate_gtk/main.py", line 54, in main
    app = application_factory(graph)
  File "/usr/lib/python3.5/site-packages/tomate/app.py", line 69, in application_factory
    app = graph.get(specification)
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 238, in get
    return self.acquire(specification, arguments=arguments)
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 203, in acquire
    dependency_specification
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 203, in acquire
    dependency_specification
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 203, in acquire
    dependency_specification
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 224, in acquire
    instance = provider(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/wiring/providers.py", line 77, in __call__
    return self.factory(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tomate/config.py", line 168, in provide_parser
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 9, in <module>
    load_entry_point('tomate-gtk==0.3.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/lib/python3.5/site-packages/tomate_gtk/main.py", line 64, in main
    raise err
  File "/usr/lib/python3.5/site-packages/tomate_gtk/main.py", line 54, in main
    app = application_factory(graph)
  File "/usr/lib/python3.5/site-packages/tomate/app.py", line 69, in application_factory
    app = graph.get(specification)
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 238, in get
    return self.acquire(specification, arguments=arguments)
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 203, in acquire
    dependency_specification
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 203, in acquire
    dependency_specification
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 203, in acquire
    dependency_specification
  File "/usr/lib/python3.5/site-packages/wiring/graph.py", line 224, in acquire
    instance = provider(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/wiring/providers.py", line 77, in __call__
    return self.factory(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tomate/config.py", line 168, in provide_parser
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
```
Thanks.

**Comment by eliostvs** [comment]
You are right. The name of the module has changed. I will fix this. Thanks.

**Comment by AlexTalker** [comment]
@eliostvs No problem. I'll appreciate if you notice me about fix the bug.

**Comment by eliostvs** [comment]
I've changed the code to work with python 2 and 3. It is still in the branch develop. I hope make a new release until the end of this year.

**Comment by AlexTalker** [comment]
@eliostvs Sorry for late answer :smile:  sounds good...end of this year is coming!

**Comment by eliostvs** [comment]
I just release a new version. Try to update.

**Comment by AlexTalker** [comment]
@eliostvs Seems like it works fine, thank you very much! :+1: 
Also, I've got a little warning, not sure if it's helpful to fix it but probably:
```
/usr/bin/tomate-gtk:9: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  load_entry_point('tomate-gtk==0.4.0', 'console_scripts', 'tomate-gtk')()
/usr/lib/python3.5/site-packages/pkg_resources/__init__.py:2709: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  return ep.load()
```
It's clear what the thing wants :smile: 
Have a lucky coding!

**Comment by shookees** [comment]
While trying to install `python3-tomate tomate3-gtk tomate-*3` I received the following error for Ubuntu 14.04:

    The following packages have unmet dependencies:
     python3-tomate : Depends: python-all (>= 3.2) but 2.7.5-5ubuntu3 is to be installed
     tomate3-gtk : Depends: python-all (>= 3.2) but 2.7.5-5ubuntu3 is to be installed

Thing is, for Ubuntu systems, there exists `python-all` and `python3-all` packages.
The following lines in [tomate-gtk.dsc](https://github.com/eliostvs/tomate-gtk/blob/f0a512acab395d33832f5c813922ecfaa24daf4b/packages/tomate-gtk.dsc#L9) and [debian.control](https://github.com/eliostvs/tomate-gtk/blob/f0a512acab395d33832f5c813922ecfaa24daf4b/packages/debian.control#L6) reference it. Is it as simple as renaming the package names or does it require some distribution based splitting? Also would it be rational to keep a separate repository for core, gtk implementation and packaging?

**Comment by eliostvs** [comment]
I released a new version today without some the alert warnings.

**Comment by eliostvs** [comment]
@shookees It was a good idea move the packing metadata to another repository. Thanks!

**Comment by shookees** [comment]
Thanks, @eliostvs, I can confirm that the error does not show up anymore
