### ISSUE TITLE
Cannot start in Ubuntu 17.10

### ISSUE THREAD

**Issue by novalu** [eliostvs/tomate-gtk#24]
Hello, thank you for your work, I used this app for the long time, however in Ubuntu (Kubuntu) 17.10 Tomate refuses to start with this stacktrace:

```
Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 11, in <module>
    load_entry_point('tomate-gtk==0.7.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/tomate_gtk/__main__.py", line 3, in <module>
    from .main import main
  File "/usr/lib/python3/dist-packages/tomate_gtk/main.py", line 14, in <module>
    from tomate.app import Application
ModuleNotFoundError: No module named 'tomate'
```

I thought it caused some broken packages after update from 17.04 to 17.10, but it occurs on clean 17.10 install too. Have you any ideas? Thanks!

**Comment by eliostvs** [comment]
Hi, sorry for that, there isn't a repo for Ubuntu 17.10. I should be working now. At least is working in Lubuntu 17.10. Let me know if you still have problems.

**Comment by novalu** [comment]
Awesome! It's working now. Thank you very much!

**Comment by alexbs** [comment]
Similar issue when trying to start in Ubuntu 20.04 (upgraded today from 19.10)

```
Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 11, in <module>
    load_entry_point('tomate-gtk==0.11.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/tomate_gtk/__main__.py", line 1, in <module>
    from .main import main
  File "/usr/lib/python3/dist-packages/tomate_gtk/main.py", line 10, in <module>
    from tomate.app import Application
ModuleNotFoundError: No module named 'tomate'
```
Thank You for such useful app!!! I adore it !!!
