### ISSUE TITLE
Python 3.7 breaks tomate-gtk.

### ISSUE THREAD

**Issue by Zerophase** [eliostvs/tomate-gtk#28]
Doesn't seem to be working with a system upgraded to Python 3.7.

**Comment by eliostvs** [comment]
Hi, which are you distribution? Could you open the app from the command line, `tomate-gtk 2> tomate.log`, and send me the output?

**Comment by Zerophase** [comment]
I'm on Arch Linux.

```
Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 11, in <module>
    load_entry_point('tomate-gtk==0.8.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/tomate_gtk/__main__.py", line 3, in <module>
    from .main import main
  File "/usr/lib/python3.7/site-packages/tomate_gtk/main.py", line 14, in <module>
    from tomate.app import Application
ModuleNotFoundError: No module named 'tomate'

```

**Comment by eliostvs** [comment]
I tested on a fresh Arch install and it seems that is working. From your message it seems that the package *python-tomate* is missing. Could you try to list the contents of the this package with `pacman -Ql python-tomate`?

**Comment by Zerophase** [comment]
Silly me. Looks like I missed a few packages needing updates.
