### ISSUE TITLE
No module named "wiring"

### ISSUE THREAD

**Issue by ImpracticalDogg** [eliostvs/tomate-gtk#43]
Ubuntu 18.04. Pulling from 20.04. Tried sudo apt-get install tomate-gtk --reinstall 
Tomate has stopped working. Starting from the command line I get:
`Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 11, in <module>
    load_entry_point('tomate-gtk==0.12.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/tomate/__main__.py", line 1, in <module>
    from .main import main
  File "/usr/lib/python3/dist-packages/tomate/main.py", line 11, in <module>
    from wiring.scanning import scan_to_graph
ModuleNotFoundError: No module named 'wiring'`

**Comment by ImpracticalDogg** [comment]
Updated this morning and it works fine now. Thanks! I can't work without your app :)

**Comment by eliostvs** [comment]
Hi. Good to known that is working. I've found some small issues in the packages metadata in many distributions (Ubuntu, Fedora, Opensuse, etc) and I'm still doing some installations tests. Thanks for reaching out!
