### ISSUE TITLE
Problems with matplotlib backend

### ISSUE THREAD

**Issue by isomerase** [eliostvs/tomate-gtk#6]
I'm running into this error:
` ~  tomate-gtk
Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 9, in <module>
    load_entry_point('tomate-gtk==0.5.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 550, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2710, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/__main__.py", line 3, in <module>
    from .main import main
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 11, in <module>
    from gi.repository import Gdk
  File "/usr/lib/python2.7/dist-packages/gi/repository/__init__.py", line 25, in <module>
    from ..importer import DynamicImporter
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 27, in <module>
    from .module import DynamicModule
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 59, in <module>
    from .types import \
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 44, in <module>
    from . import _propertyhelper as propertyhelper
  File "/usr/lib/python2.7/dist-packages/gi/_propertyhelper.py", line 23, in <module>
    import gi._gi
  File "/usr/lib/python2.7/dist-packages/gi/gi/__init__.py", line 39, in <module>
    raise ImportError(_static_binding_error)
ImportError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183`

I've followed the advice from [these](https://stackoverflow.com/questions/15557658/import-errors-with-python-and-gtk-3) [links](https://github.com/aplpy/aplpy/issues/103) and changed my matplotlib backend to use 'pdf' but I still have the same error.

` ~  which python                              
/home/richard/Apps/anaconda2/bin/python`

**Comment by eliostvs** [comment]
Hi. Sorry for the late answer. Which is your distribution? Have you try to install the native package?

**Comment by isomerase** [comment]
At the time, I was using Debian. I have since switched to Ubuntu. I just installed it using the directions for Ubuntu and it runs fine.
