### ISSUE TITLE
"No module named wiring" issue returns on Ubuntu 14.04

### ISSUE THREAD

**Issue by Rondo5000** [eliostvs/tomate-gtk#7]
Hi.  It seems that with the latest update has brought back the "No module named wiring" issue.  Any help would be greatly appreciated!:

`Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 9, in <module>
    load_entry_point('tomate-gtk==0.5.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/__main__.py", line 3, in <module>
    from .main import main
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 13, in <module>
    from tomate.app import Application, ApplicationModule
  File "/usr/lib/python2.7/dist-packages/tomate/app.py", line 4, in <module>
    from wiring import inject, SingletonScope, Module
ImportError: No module named wiring`

**Comment by eliostvs** [comment]
Sorry for that. I'm having trouble to build packages for all Ubuntu versions. The package for ubuntu 16.04 still broken but for 14.04 it should be working now.

**Comment by Rondo5000** [comment]
Unfortunately even after the update and a full reinstall I'm still receiving the same error on Ubuntu 14.04.  Best of luck with the updates!

**Comment by eliostvs** [comment]
Please, try to clean and update the repositories.

**Comment by Rondo5000** [comment]
And now it works!  The last set of updates did the trick.  Thank you so very much.

**Comment by eliostvs** [comment]
Great! Sorry again for the trouble.
